### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by techietrader** [fpingham/dataset-cleaner#1]
Hi,
Can I get to look into the data please? I mean the format and a glimpse at the images

**Comment by fpingham** [comment]
What do you mean? Which data? These are both public datasets.

**Comment by techietrader** [comment]
Hi,
Yes! Apologies. 

Secondly, I was a bit confused between the two files
- Duplicates.ipynb
- Data_Cleaner.ipynb
Can you explain please as to what is the second one for?

**Comment by fpingham** [comment]
Duplicates is gone! There is only one now :+1:
